services:
  backend:
    image: ${DOCKER_IMAGE:-ghcr.io/${GITHUB_REPOSITORY:-studyfundorg/platform}:main}
    container_name: studyfund-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env.backend
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - studyfund-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    command: >
      sh -c "if [ \"$NODE_ENV\" = \"production\" ]; then
               npm run start:prod;
             else
               npm run start:dev;
             fi"

networks:
  studyfund-network:
    driver: bridge 