services:
  backend:
    image: ${DOCKER_IMAGE:-ghcr.io/${GITHUB_REPOSITORY:-studyfundorg/backend}:main}
    container_name: studyfund-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env.backend
    volumes:
      - /mnt/volume_lon1_04/studyfund/backend/node_modules:/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - studyfund-network
    command: >
      sh -c "if [ \"$NODE_ENV\" = \"production\" ]; then
               npm run start:prod;
             else
               npm run start:dev;
             fi"

networks:
  studyfund-network:
    driver: bridge 